export const TOP_TOUR_REQUEST = 'TOP_TOUR_REQUEST';
export const TOP_TOUR_SUCCESS = 'TOP_TOUR_SUCCESS';
export const TOP_TOUR_FAIL = 'TOP_TOUR_FAIL';

export const TOUR_DETAILS_REQUEST = 'TOUR_DETAILS_REQUEST';
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS';
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL';
